# 测试环境
env:
  base_url: http://192.168.46.5:41805/
  time_out: 30
  retry: 3
  headers:
    Content-Type: application/json

# 登录接口
api:
  login:
    url: http://192.168.46.5:41805/prod-api/auth/login
    method: POST
    headers:
      Content-Type: application/json